name: Release

on:
  push:
    branches:
    - none

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    outputs:
      version: ${{ steps.get_tag.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get latest tag (semantic version)
        id: get_tag
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v' 
